INSERT INTO sys_menus (
    id, parent_id, path, name, hidden, component, sort, title, icon, menu_type, status, permission
)
VALUES
    (1, NULL, '/dashboard', 'dashboard', false, 'view/dashboard/index.vue', 10, 'Dashboard', 'odometer', 'page', 'enabled', 'system:dashboard:view'),

    (10, NULL, '/organization', 'organization', false, 'Layout', 20, 'Organization', 'users', 'directory', 'enabled', NULL),
    (11, 10, '/users', 'users', false, 'view/users/index.vue', 10, 'Users', 'user', 'page', 'enabled', 'system:user:list'),
    (1101, 11, '', 'users:create', true, '', 10, 'Create user', '', 'action', 'enabled', 'system:user:create'),
    (1102, 11, '', 'users:update', true, '', 20, 'Update user', '', 'action', 'enabled', 'system:user:update'),
    (1103, 11, '', 'users:delete', true, '', 30, 'Delete user', '', 'action', 'enabled', 'system:user:delete'),
    (1104, 11, '', 'users:reset-password', true, '', 40, 'Reset password', '', 'action', 'enabled', 'system:user:reset-password'),
    (1105, 11, '', 'users:assign-roles', true, '', 50, 'Assign roles', '', 'action', 'enabled', 'system:user:assign-roles'),
    (12, 10, '/roles', 'roles', false, 'view/roles/index.vue', 20, 'Roles', 'shield', 'page', 'enabled', 'system:role:list'),
    (1201, 12, '', 'roles:create', true, '', 10, 'Create role', '', 'action', 'enabled', 'system:role:create'),
    (1202, 12, '', 'roles:update', true, '', 20, 'Update role', '', 'action', 'enabled', 'system:role:update'),
    (1203, 12, '', 'roles:delete', true, '', 30, 'Delete role', '', 'action', 'enabled', 'system:role:delete'),
    (1204, 12, '', 'roles:menus-read', true, '', 40, 'Read role menus', '', 'action', 'enabled', 'system:role:menus-read'),
    (1205, 12, '', 'roles:menus-update', true, '', 50, 'Update role menus', '', 'action', 'enabled', 'system:role:update-permission'),
    (1206, 12, '', 'roles:depts-read', true, '', 60, 'Read role departments', '', 'action', 'enabled', 'system:role:depts-read'),
    (1207, 12, '', 'roles:depts-update', true, '', 70, 'Update role departments', '', 'action', 'enabled', 'system:role:depts-update'),
    (1208, 12, '', 'roles:users-read', true, '', 80, 'Read role users', '', 'action', 'enabled', 'system:role:list-users'),
    (1209, 12, '', 'roles:users-update', true, '', 90, 'Assign role users', '', 'action', 'enabled', 'system:role:assign-users'),
    (13, 10, '/departments', 'departments', false, 'view/departments/index.vue', 30, 'Departments', 'building', 'page', 'enabled', 'system:dept:list'),
    (1301, 13, '', 'departments:create', true, '', 10, 'Create department', '', 'action', 'enabled', 'system:dept:create'),
    (1302, 13, '', 'departments:get', true, '', 20, 'Get department', '', 'action', 'enabled', 'system:dept:get'),
    (1303, 13, '', 'departments:update', true, '', 30, 'Update department', '', 'action', 'enabled', 'system:dept:update'),
    (1304, 13, '', 'departments:delete', true, '', 40, 'Delete department', '', 'action', 'enabled', 'system:dept:delete'),

    (20, NULL, '/access', 'access-control', false, 'Layout', 30, 'Access Control', 'lock', 'directory', 'enabled', NULL),
    (21, 20, '/menus', 'menus', false, 'view/menus/index.vue', 10, 'Access Catalog', 'menu', 'page', 'enabled', 'system:menu:list'),

    (30, NULL, '/system', 'system', false, 'Layout', 40, 'System', 'settings', 'directory', 'enabled', NULL),
    (31, 30, '/params', 'params', false, 'view/params/index.vue', 10, 'Params', 'sliders', 'page', 'enabled', 'system:param:list'),
    (3101, 31, '', 'params:create', true, '', 10, 'Create param', '', 'action', 'enabled', 'system:param:create'),
    (3102, 31, '', 'params:get', true, '', 20, 'Get param', '', 'action', 'enabled', 'system:param:get'),
    (3103, 31, '', 'params:update', true, '', 30, 'Update param', '', 'action', 'enabled', 'system:param:update'),
    (3104, 31, '', 'params:delete', true, '', 40, 'Delete param', '', 'action', 'enabled', 'system:param:delete'),
    (3105, 31, '', 'params:batch-delete', true, '', 50, 'Batch delete params', '', 'action', 'enabled', 'system:param:batch-delete'),
    (32, 30, '/dictionaries', 'dictionaries', false, 'view/dictionaries/index.vue', 20, 'Dictionaries', 'book', 'page', 'enabled', 'system:dictionary:list'),
    (3201, 32, '', 'dictionaries:create', true, '', 10, 'Create dictionary', '', 'action', 'enabled', 'system:dictionary:create'),
    (3202, 32, '', 'dictionaries:update', true, '', 20, 'Update dictionary', '', 'action', 'enabled', 'system:dictionary:update'),
    (3203, 32, '', 'dictionaries:delete', true, '', 30, 'Delete dictionary', '', 'action', 'enabled', 'system:dictionary:delete'),
    (3204, 32, '', 'dictionaries:import', true, '', 40, 'Import dictionaries', '', 'action', 'enabled', 'system:dictionary:import'),
    (3205, 32, '', 'dictionaries:export', true, '', 50, 'Export dictionary', '', 'action', 'enabled', 'system:dictionary:export'),
    (3211, 32, '', 'dictionary-details:create', true, '', 60, 'Create dictionary detail', '', 'action', 'enabled', 'system:dictionary-detail:create'),
    (3212, 32, '', 'dictionary-details:update', true, '', 70, 'Update dictionary detail', '', 'action', 'enabled', 'system:dictionary-detail:update'),
    (3213, 32, '', 'dictionary-details:delete', true, '', 80, 'Delete dictionary detail', '', 'action', 'enabled', 'system:dictionary-detail:delete'),
    (33, 30, '/files', 'files', false, 'view/files/index.vue', 30, 'Files', 'folder', 'page', 'enabled', 'system:file:list'),
    (3301, 33, '', 'files:import-url', true, '', 10, 'Import file URL', '', 'action', 'enabled', 'system:file:import-url'),
    (3302, 33, '', 'files:upload', true, '', 20, 'Upload file', '', 'action', 'enabled', 'system:file:upload'),
    (3303, 33, '', 'files:delete', true, '', 30, 'Delete file', '', 'action', 'enabled', 'system:file:delete'),
    (3304, 33, '', 'files:rename', true, '', 40, 'Rename file', '', 'action', 'enabled', 'system:file:rename'),
    (3305, 33, '', 'file-categories:create', true, '', 50, 'Create file category', '', 'action', 'enabled', 'system:attachment-category:create'),
    (3306, 33, '', 'file-categories:delete', true, '', 60, 'Delete file category', '', 'action', 'enabled', 'system:attachment-category:delete'),
    (34, 30, '/system-config', 'system-config', false, 'view/system/config.vue', 40, 'System Config', 'settings', 'page', 'enabled', 'system:config:get'),
    (3401, 34, '', 'system-config:update', true, '', 10, 'Update system config', '', 'action', 'enabled', 'system:config:update'),
    (35, 30, '/system-state', 'system-state', false, 'view/system/state.vue', 50, 'System Status', 'activity', 'page', 'enabled', 'system:state:get'),
    (3501, 35, '', 'system-state:reload', true, '', 10, 'Reload system', '', 'action', 'enabled', 'system:state:reload'),

    (40, NULL, '/audit', 'audit', false, 'Layout', 50, 'Audit', 'history', 'directory', 'enabled', NULL),
    (41, 40, '/login-logs', 'login-logs', false, 'view/logs/login.vue', 10, 'Login Logs', 'log-in', 'page', 'enabled', 'system:login-log:list'),
    (4101, 41, '', 'login-logs:delete', true, '', 10, 'Delete login logs', '', 'action', 'enabled', 'system:login-log:delete'),
    (42, 40, '/operation-logs', 'operation-logs', false, 'view/logs/operation.vue', 20, 'Operation Logs', 'clipboard-list', 'page', 'enabled', 'system:operation-log:list'),
    (4201, 42, '', 'operation-logs:delete', true, '', 10, 'Delete operation logs', '', 'action', 'enabled', 'system:operation-log:delete');

INSERT INTO sys_menu_apis (menu_id, method, path_pattern)
VALUES
    (11, 'GET', '/api/users'),
    (1101, 'POST', '/api/users'),
    (1102, 'PUT', '/api/users/{id}'),
    (1103, 'DELETE', '/api/users/{id}'),
    (1104, 'POST', '/api/users/{id}/password/reset'),
    (1105, 'PUT', '/api/users/{id}/roles'),

    (12, 'GET', '/api/roles'),
    (1201, 'POST', '/api/roles'),
    (1202, 'PUT', '/api/roles/{id}'),
    (1203, 'DELETE', '/api/roles/{id}'),
    (1204, 'GET', '/api/roles/{id}/menus'),
    (1205, 'PUT', '/api/roles/{id}/menus'),
    (1206, 'GET', '/api/roles/{id}/depts'),
    (1207, 'PUT', '/api/roles/{id}/depts'),
    (1208, 'GET', '/api/roles/{id}/users'),
    (1209, 'PUT', '/api/roles/{id}/users'),

    (13, 'GET', '/api/depts'),
    (1301, 'POST', '/api/depts'),
    (1302, 'GET', '/api/depts/{id}'),
    (1303, 'PUT', '/api/depts/{id}'),
    (1304, 'DELETE', '/api/depts/{id}'),
    (21, 'GET', '/api/menus/tree'),

    (31, 'GET', '/api/params'),
    (31, 'GET', '/api/params/by-key'),
    (3101, 'POST', '/api/params'),
    (3102, 'GET', '/api/params/{id}'),
    (3103, 'PUT', '/api/params/{id}'),
    (3104, 'DELETE', '/api/params/{id}'),
    (3105, 'DELETE', '/api/params/batch'),

    (32, 'GET', '/api/dictionaries'),
    (32, 'GET', '/api/dictionaries/{id}'),
    (32, 'GET', '/api/dictionaries/{id}/details/tree'),
    (32, 'GET', '/api/dictionary-details/tree-by-type'),
    (32, 'GET', '/api/dictionary-details/by-parent'),
    (32, 'GET', '/api/dictionary-details/{id}'),
    (32, 'GET', '/api/dictionary-details/{id}/path'),
    (3201, 'POST', '/api/dictionaries'),
    (3202, 'PUT', '/api/dictionaries/{id}'),
    (3203, 'DELETE', '/api/dictionaries/{id}'),
    (3204, 'POST', '/api/dictionaries/import'),
    (3205, 'GET', '/api/dictionaries/{id}/export'),
    (3211, 'POST', '/api/dictionary-details'),
    (3212, 'PUT', '/api/dictionary-details/{id}'),
    (3213, 'DELETE', '/api/dictionary-details/{id}'),

    (33, 'GET', '/api/files'),
    (33, 'GET', '/api/attachment-categories'),
    (3301, 'POST', '/api/files/import-url'),
    (3302, 'POST', '/api/files/upload'),
    (3303, 'DELETE', '/api/files/{id}'),
    (3304, 'PATCH', '/api/files/{id}/name'),
    (3305, 'POST', '/api/attachment-categories'),
    (3306, 'DELETE', '/api/attachment-categories/{id}'),

    (34, 'GET', '/api/system/config'),
    (3401, 'PUT', '/api/system/config'),
    (35, 'GET', '/api/system/server-info'),
    (3501, 'POST', '/api/system/reload'),

    (41, 'GET', '/api/login-logs'),
    (41, 'GET', '/api/login-logs/{id}'),
    (4101, 'DELETE', '/api/login-logs'),
    (4101, 'DELETE', '/api/login-logs/{id}'),
    (42, 'GET', '/api/operation-logs'),
    (4201, 'DELETE', '/api/operation-logs'),
    (4201, 'DELETE', '/api/operation-logs/{id}');
