CREATE TEMP TABLE _permission_api_seed (
    module_key TEXT NOT NULL,
    resource TEXT NOT NULL,
    action TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    permission_type TEXT NOT NULL,
    method TEXT NOT NULL,
    path_pattern TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _permission_api_seed (module_key, resource, action, code, name, permission_type, method, path_pattern)
VALUES
('system', 'user', 'list', 'system:user:list', 'List Users', 'action', 'GET', '/api/users'),
('system', 'user', 'create', 'system:user:create', 'Create User', 'action', 'POST', '/api/users'),
('system', 'user', 'update', 'system:user:update', 'Update User', 'action', 'PUT', '/api/users/{id}'),
('system', 'user', 'delete', 'system:user:delete', 'Delete User', 'action', 'DELETE', '/api/users/{id}'),
('system', 'user', 'reset-password', 'system:user:reset-password', 'Reset User Password', 'action', 'POST', '/api/users/{id}/password/reset'),
('system', 'user', 'assign-roles', 'system:user:assign-roles', 'Assign User Roles', 'action', 'PUT', '/api/users/{id}/roles'),
('system', 'role', 'list', 'system:role:list', 'List Roles', 'action', 'GET', '/api/roles'),
('system', 'role', 'create', 'system:role:create', 'Create Role', 'action', 'POST', '/api/roles'),
('system', 'role', 'update', 'system:role:update', 'Update Role', 'action', 'PUT', '/api/roles/{id}'),
('system', 'role', 'delete', 'system:role:delete', 'Delete Role', 'action', 'DELETE', '/api/roles/{id}'),
('system', 'role', 'permissions-read', 'system:role:permissions-read', 'Read Role Permissions', 'action', 'GET', '/api/roles/{id}/permissions'),
('system', 'role', 'permissions-update', 'system:role:permissions-update', 'Update Role Permissions', 'action', 'PUT', '/api/roles/{id}/permissions'),
('system', 'role', 'depts-read', 'system:role:depts-read', 'Read Role Departments', 'action', 'GET', '/api/roles/{id}/depts'),
('system', 'role', 'depts-update', 'system:role:depts-update', 'Update Role Departments', 'action', 'PUT', '/api/roles/{id}/depts'),
('system', 'role', 'list-users', 'system:role:list-users', 'List Role Users', 'action', 'GET', '/api/roles/{id}/users'),
('system', 'role', 'assign-users', 'system:role:assign-users', 'Assign Role Users', 'action', 'PUT', '/api/roles/{id}/users'),
('system', 'role', 'update-permission', 'system:role:update-permission', 'Save Role Menu Permissions', 'action', 'PUT', '/api/roles/{id}/permissions'),
('system', 'permission', 'list', 'system:permission:list', 'List Permissions', 'action', 'GET', '/api/permissions'),
('system', 'permission', 'create', 'system:permission:create', 'Create Permission', 'action', 'POST', '/api/permissions'),
('system', 'permission', 'update', 'system:permission:update', 'Update Permission', 'action', 'PUT', '/api/permissions/{id}'),
('system', 'permission', 'delete', 'system:permission:delete', 'Delete Permission', 'action', 'DELETE', '/api/permissions/{id}'),
('system', 'permission', 'apis-read', 'system:permission:apis-read', 'Read Permission APIs', 'action', 'GET', '/api/permissions/{id}/apis'),
('system', 'permission', 'apis-update', 'system:permission:apis-update', 'Update Permission APIs', 'action', 'PUT', '/api/permissions/{id}/apis'),
('system', 'dept', 'list', 'system:dept:list', 'List Departments', 'action', 'GET', '/api/depts'),
('system', 'dept', 'create', 'system:dept:create', 'Create Department', 'action', 'POST', '/api/depts'),
('system', 'dept', 'get', 'system:dept:get', 'Get Department', 'action', 'GET', '/api/depts/{id}'),
('system', 'dept', 'update', 'system:dept:update', 'Update Department', 'action', 'PUT', '/api/depts/{id}'),
('system', 'dept', 'delete', 'system:dept:delete', 'Delete Department', 'action', 'DELETE', '/api/depts/{id}'),
('system', 'menu', 'list', 'system:menu:list', 'List Menus', 'action', 'GET', '/api/menus'),
('system', 'menu', 'create', 'system:menu:create', 'Create Menu', 'action', 'POST', '/api/menus'),
('system', 'menu', 'update', 'system:menu:update', 'Update Menu', 'action', 'PUT', '/api/menus/{id}'),
('system', 'menu', 'delete', 'system:menu:delete', 'Delete Menu', 'action', 'DELETE', '/api/menus/{id}'),
('system', 'menu', 'tree', 'system:menu:tree', 'Menu Tree', 'action', 'GET', '/api/menus/tree'),
('system', 'menu', 'get-roles', 'system:menu:get-roles', 'Get Menu Roles', 'action', 'GET', '/api/menus/{id}/roles'),
('system', 'menu', 'set-roles', 'system:menu:set-roles', 'Set Menu Roles', 'action', 'PUT', '/api/menus/{id}/roles'),
('system', 'api', 'list', 'system:api:list', 'List APIs', 'action', 'GET', '/api/routes'),
('system', 'api', 'create', 'system:api:create', 'Create API', 'action', 'POST', '/api/routes'),
('system', 'api', 'get', 'system:api:get', 'Get API', 'action', 'GET', '/api/routes/{id}'),
('system', 'api', 'update', 'system:api:update', 'Update API', 'action', 'PUT', '/api/routes/{id}'),
('system', 'api', 'delete', 'system:api:delete', 'Delete API', 'action', 'DELETE', '/api/routes/{id}'),
('system', 'api', 'batch-delete', 'system:api:batch-delete', 'Batch Delete APIs', 'action', 'DELETE', '/api/routes/batch'),
('system', 'api', 'list-all', 'system:api:list-all', 'List All APIs', 'action', 'GET', '/api/routes/all'),
('system', 'api', 'groups', 'system:api:groups', 'API Groups', 'action', 'GET', '/api/routes/groups'),
('system', 'api', 'list-roles', 'system:api:list-roles', 'List API Roles', 'action', 'GET', '/api/routes/roles'),
('system', 'api', 'assign-roles', 'system:api:assign-roles', 'Assign API Roles', 'action', 'PUT', '/api/routes/roles'),
('system', 'api', 'authority', 'system:api:authority', 'Authority APIs', 'action', 'GET', '/api/routes/authority'),
('system', 'api', 'role-matrix', 'system:api:role-matrix', 'API Role Matrix', 'action', 'GET', '/api/routes/role-matrix'),
('system', 'api', 'casbin-refresh', 'system:api:casbin-refresh', 'Refresh API Policy', 'action', 'POST', '/api/routes/casbin/refresh'),
('system', 'attachment-category', 'list', 'system:attachment-category:list', 'List Attachment Categories', 'action', 'GET', '/api/attachment-categories'),
('system', 'attachment-category', 'create', 'system:attachment-category:create', 'Create Attachment Category', 'action', 'POST', '/api/attachment-categories'),
('system', 'attachment-category', 'delete', 'system:attachment-category:delete', 'Delete Attachment Category', 'action', 'DELETE', '/api/attachment-categories/{id}'),
('system', 'param', 'list', 'system:param:list', 'List Params', 'action', 'GET', '/api/params'),
('system', 'param', 'create', 'system:param:create', 'Create Param', 'action', 'POST', '/api/params'),
('system', 'param', 'get', 'system:param:get', 'Get Param', 'action', 'GET', '/api/params/{id}'),
('system', 'param', 'update', 'system:param:update', 'Update Param', 'action', 'PUT', '/api/params/{id}'),
('system', 'param', 'delete', 'system:param:delete', 'Delete Param', 'action', 'DELETE', '/api/params/{id}'),
('system', 'param', 'get-by-key', 'system:param:get-by-key', 'Get Param By Key', 'action', 'GET', '/api/params/by-key'),
('system', 'param', 'batch-delete', 'system:param:batch-delete', 'Batch Delete Params', 'action', 'DELETE', '/api/params/batch'),
('system', 'dictionary', 'list', 'system:dictionary:list', 'List Dictionaries', 'action', 'GET', '/api/dictionaries'),
('system', 'dictionary', 'create', 'system:dictionary:create', 'Create Dictionary', 'action', 'POST', '/api/dictionaries'),
('system', 'dictionary', 'get', 'system:dictionary:get', 'Get Dictionary', 'action', 'GET', '/api/dictionaries/{id}'),
('system', 'dictionary', 'update', 'system:dictionary:update', 'Update Dictionary', 'action', 'PUT', '/api/dictionaries/{id}'),
('system', 'dictionary', 'delete', 'system:dictionary:delete', 'Delete Dictionary', 'action', 'DELETE', '/api/dictionaries/{id}'),
('system', 'dictionary', 'import', 'system:dictionary:import', 'Import Dictionaries', 'action', 'POST', '/api/dictionaries/import'),
('system', 'dictionary', 'export', 'system:dictionary:export', 'Export Dictionary', 'action', 'GET', '/api/dictionaries/{id}/export'),
('system', 'dictionary', 'details-tree', 'system:dictionary:details-tree', 'Dictionary Detail Tree', 'action', 'GET', '/api/dictionaries/{id}/details/tree'),
('system', 'dictionary-detail', 'create', 'system:dictionary-detail:create', 'Create Dictionary Detail', 'action', 'POST', '/api/dictionary-details'),
('system', 'dictionary-detail', 'tree-by-type', 'system:dictionary-detail:tree-by-type', 'Dictionary Detail Tree By Type', 'action', 'GET', '/api/dictionary-details/tree-by-type'),
('system', 'dictionary-detail', 'by-parent', 'system:dictionary-detail:by-parent', 'Dictionary Details By Parent', 'action', 'GET', '/api/dictionary-details/by-parent'),
('system', 'dictionary-detail', 'get', 'system:dictionary-detail:get', 'Get Dictionary Detail', 'action', 'GET', '/api/dictionary-details/{id}'),
('system', 'dictionary-detail', 'update', 'system:dictionary-detail:update', 'Update Dictionary Detail', 'action', 'PUT', '/api/dictionary-details/{id}'),
('system', 'dictionary-detail', 'delete', 'system:dictionary-detail:delete', 'Delete Dictionary Detail', 'action', 'DELETE', '/api/dictionary-details/{id}'),
('system', 'dictionary-detail', 'path', 'system:dictionary-detail:path', 'Dictionary Detail Path', 'action', 'GET', '/api/dictionary-details/{id}/path'),
('system', 'file', 'list', 'system:file:list', 'List Files', 'action', 'GET', '/api/files'),
('system', 'file', 'import-url', 'system:file:import-url', 'Import File URL', 'action', 'POST', '/api/files/import-url'),
('system', 'file', 'upload', 'system:file:upload', 'Upload File', 'action', 'POST', '/api/files/upload'),
('system', 'file', 'delete', 'system:file:delete', 'Delete File', 'action', 'DELETE', '/api/files/{id}'),
('system', 'file', 'rename', 'system:file:rename', 'Rename File', 'action', 'PATCH', '/api/files/{id}/name'),
('system', 'login-log', 'list', 'system:login-log:list', 'List Login Logs', 'action', 'GET', '/api/login-logs'),
('system', 'login-log', 'batch-delete', 'system:login-log:batch-delete', 'Batch Delete Login Logs', 'action', 'DELETE', '/api/login-logs'),
('system', 'login-log', 'get', 'system:login-log:get', 'Get Login Log', 'action', 'GET', '/api/login-logs/{id}'),
('system', 'login-log', 'delete', 'system:login-log:delete', 'Delete Login Log', 'action', 'DELETE', '/api/login-logs/{id}'),
('system', 'operation-log', 'list', 'system:operation-log:list', 'List Operation Logs', 'action', 'GET', '/api/operation-logs'),
('system', 'operation-log', 'batch-delete', 'system:operation-log:batch-delete', 'Batch Delete Operation Logs', 'action', 'DELETE', '/api/operation-logs'),
('system', 'operation-log', 'delete', 'system:operation-log:delete', 'Delete Operation Log', 'action', 'DELETE', '/api/operation-logs/{id}'),
('system', 'config', 'get', 'system:config:get', 'Get System Config', 'action', 'GET', '/api/system/config'),
('system', 'config', 'update', 'system:config:update', 'Update System Config', 'action', 'PUT', '/api/system/config'),
('system', 'state', 'get', 'system:state:get', 'Get System State', 'action', 'GET', '/api/system/server-info'),
('system', 'state', 'reload', 'system:state:reload', 'Reload System', 'action', 'POST', '/api/system/reload');

INSERT INTO sys_permissions (module_key, resource, action, code, name, type, status)
SELECT DISTINCT module_key, resource, action, code, name, permission_type, 'enabled'
FROM _permission_api_seed
ON CONFLICT (code) DO NOTHING;

INSERT INTO sys_permission_apis (permission_id, method, path_pattern)
SELECT p.id, seed.method, seed.path_pattern
FROM _permission_api_seed seed
JOIN sys_permissions p ON p.code = seed.code
ON CONFLICT DO NOTHING;
